name: Test Runner

on: [push]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, world!"

